// Copyright (C) 2025 CypherGoat
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package views

var ExchangesList = []Exchange{
	{
		Name:                  "Swapuz",
		ShortCode:             "swapuz",
		KYCScore:              0,
		URL:                   "https://www.swapuz.com",
		LogoURL:               "/exchanges/swapuz.png",
		NoTextURL:             "/exchanges/no-text/swapuz.png",
		Description:           "Swapuz is a crypto swap platform that was designed to preserve the complete anonymity of its users.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/swapuz.com",
		TrustpilotRating:      4.6,
		TrustpilotReviewCount: 107,
	},
	{
		Name:                  "AlfaCash",
		ShortCode:             "alfacash",
		KYCScore:              2,
		URL:                   "https://www.alfacash.com",
		LogoURL:               "/exchanges/alfacash.svg",
		NoTextURL:             "/exchanges/no-text/alfacash.jpg",
		Description:           "A reliable cryptocurrency exchange offering competitive rates and fast transactions.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/alfa.cash",
		TrustpilotRating:      3.4,
		TrustpilotReviewCount: 74,
	},
	{
		Name:                  "ChangeHero",
		ShortCode:             "changehero",
		KYCScore:              2,
		URL:                   "https://changehero.io",
		LogoURL:               "/exchanges/changehero.svg",
		NoTextURL:             "/exchanges/no-text/changehero.jpeg",
		Description:           "Fast and secure cryptocurrency exchange with no registration required.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/changehero.io",
		TrustpilotRating:      4.3,
		TrustpilotReviewCount: 419,
	},
	{
		Name:                  "ChangeNOW",
		ShortCode:             "changenow",
		KYCScore:              2,
		URL:                   "https://changenow.io",
		LogoURL:               "/exchanges/changenow.svg",
		NoTextURL:             "",
		Description:           "Limitless crypto exchange with over 500 cryptocurrencies and no registration.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/changenow.io",
		TrustpilotRating:      4.5,
		TrustpilotReviewCount: 12737,
	},
	{
		Name:                  "FixedFloat",
		ShortCode:             "fixedfloat",
		KYCScore:              2,
		URL:                   "https://ff.io",
		LogoURL:               "/exchanges/fixedfloat-v2.svg",
		NoTextURL:             "/exchanges/no-text/fixedfloat.svg",
		Description:           "Lightning-fast cryptocurrency exchange with fixed and floating rates.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/ff.io",
		TrustpilotRating:      4.3,
		TrustpilotReviewCount: 2162,
	},
	{
		Name:                  "PegasusSwap",
		ShortCode:             "pegasusswap",
		KYCScore:              0,
		URL:                   "https://pegasusswap.com",
		LogoURL:               "/exchanges/pegasusswap.png",
		NoTextURL:             "",
		Description:           "PegasusSwap is an exchange service that will facilitate the exchange of cryptocurrencies! Speed, reliability and trust",
		CGShield:              true,
		CGAmount:              "0.1 BTC",
		CGSinStable:           false,
		CGSAmountFloat:        0.1,
		TrustpilotURL:         "https://www.trustpilot.com/review/pegasusswap.com",
		TrustpilotRating:      4.5,
		TrustpilotReviewCount: 15,
	},
	{
		Name:                  "QuickEx",
		ShortCode:             "quickex",
		KYCScore:              1,
		URL:                   "https://quickex.io",
		LogoURL:               "/exchanges/quickex.png",
		NoTextURL:             "",
		Description:           "A reliable and secure cryptocurrency exchange platform operating since 2018.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/quickex.io",
		TrustpilotRating:      4.2,
		TrustpilotReviewCount: 46,
	},
	{
		Name:                  "Nanswap",
		ShortCode:             "nanswap",
		KYCScore:              2,
		URL:                   "https://nanswap.com",
		LogoURL:               "/exchanges/nanswap.svg",
		NoTextURL:             "",
		Description:           "Simple and efficient cryptocurrency exchange with competitive rates.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/nanswap.com",
		TrustpilotRating:      4.1,
		TrustpilotReviewCount: 30,
	},
	{
		Name:                  "SimpleSwap",
		ShortCode:             "simpleswap",
		KYCScore:              2,
		URL:                   "https://simpleswap.io",
		LogoURL:               "/exchanges/simpleswap.svg",
		NoTextURL:             "/exchanges/no-text/simpleswap.png",
		Description:           "Easy-to-use cryptocurrency exchange with over 1500 cryptocurrencies.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/simpleswap.io",
		TrustpilotRating:      4.5,
		TrustpilotReviewCount: 2959,
	},
	{
		Name:                  "StealthEX",
		ShortCode:             "stealthex",
		KYCScore:              2,
		URL:                   "https://stealthex.io",
		LogoURL:               "/exchanges/stealthex.svg",
		NoTextURL:             "/exchanges/no-text/stealthex.png",
		Description:           "Anonymous crypto exchange with no registration and instant swaps.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/stealthex.io",
		TrustpilotRating:      4.5,
		TrustpilotReviewCount: 390,
	},
	{
		Name:                  "WizardSwap",
		ShortCode:             "wizardswap",
		KYCScore:              0,
		URL:                   "https://wizardswap.io",
		LogoURL:               "/exchanges/wizardswap.png",
		NoTextURL:             "",
		Description:           "Decentralized exchange focusing on privacy and security.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/wizardswap.io",
		TrustpilotRating:      3,
		TrustpilotReviewCount: 4,
	},
	{
		Name:                  "Exolix",
		ShortCode:             "exolix",
		KYCScore:              0,
		URL:                   "https://exolix.com",
		LogoURL:               "/exchanges/exolix.png",
		NoTextURL:             "/exchanges/no-text/exolix.png",
		Description:           "Cryptocurrency exchange with instant swaps and competitive rates.",
		CGShield:              true,
		CGAmount:              "0.05 BTC",
		CGSinStable:           false,
		CGSAmountFloat:        0.05,
		TrustpilotURL:         "https://www.trustpilot.com/review/exolix.com",
		TrustpilotRating:      4.5,
		TrustpilotReviewCount: 370,
	},
	{
		Name:                  "GoDex",
		ShortCode:             "godex",
		KYCScore:              1,
		URL:                   "https://godex.io/",
		LogoURL:               "/exchanges/godex.svg",
		NoTextURL:             "/exchanges/no-text/godex.jpg",
		Description:           "Cryptocurrency exchange with instant swaps and competitive rates.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/godex.io",
		TrustpilotRating:      4.4,
		TrustpilotReviewCount: 1010,
	},
	{
		Name:                  "LetsExchange",
		ShortCode:             "letsexchange",
		KYCScore:              2,
		URL:                   "https://letsexchange.io/",
		LogoURL:               "/exchanges/letsexchange.svg",
		NoTextURL:             "/exchanges/no-text/letsexchange.svg",
		Description:           "Cryptocurrency exchange with instant swaps and competitive rates.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/letsexchange.io",
		TrustpilotRating:      4.7,
		TrustpilotReviewCount: 573,
	},
	{
		Name:                  "BitcoinVN",
		ShortCode:             "bitcoinvn",
		KYCScore:              1,
		URL:                   "https://bitcoinvn.io/",
		LogoURL:               "/exchanges/bitcoinvn.png",
		NoTextURL:             "/exchanges/no-text/bitcoinvn.png",
		Description:           "Cryptocurrency exchange with instant swaps and competitive rates.",
		CGShield:              false,
		TrustpilotURL:         "https://www.trustpilot.com/review/bitcoinvn.io",
		TrustpilotRating:      4.5,
		TrustpilotReviewCount: 181,
	},
	{
		Name:                  "SilkByte",
		ShortCode:             "silkbyte",
		KYCScore:              0,
		URL:                   "https://silkbyte.io/",
		LogoURL:               "/exchanges/silkbyte.png",
		NoTextURL:             "/exchanges/no-text/silkbyte.png",
		Description:           "Unleash Crypto Freedom: Limitless, Trustworthy, and Sign-Up Free.",
		CGShield:              true,
		CGAmount:              "5000 USDC",
		CGSinStable:           true,
		CGSAmountFloat:        5000,
		TrustpilotURL:         "https://www.trustpilot.com/review/silkbyte.io",
		TrustpilotRating:      0,
		TrustpilotReviewCount: 0,
	},
}
